"use strict";

// Existing bilingual terminology, retained solely as supporting alignment evidence.
const BILINGUAL_LEXICON = [
  // Characters / MCs
  [/陈易/, ["trần dịch"]],
  [/小黑/, ["tiểu hắc"]],
  [/大白/, ["đại bạch"]],
  [/冰樱/, ["băng anh"]],
  [/白良/, ["bạch lương"]],
  [/李开阳/, ["lý khai dương"]],
  [/冰坚/, ["băng kiên"]],
  [/刘德/, ["lưu đức"]],
  [/陈昊/, ["trần hạo"]],
  [/王凌/, ["vương lăng"]],
  [/肖婉茹/, ["tiêu uyển như"]],
  [/陈楠/, ["trần nam"]],
  [/妞妞/, ["nữu nữu"]],

  // System & Game
  [/宝箱/, ["rương"]],
  [/白银宝箱/, ["rương báu bằng bạc", "rương báu bạc", "rương bạc"]],
  [/木制宝箱/, ["rương gỗ"]],
  [/击杀/, ["tiêu diệt", "giết"]],
  [/获得/, ["nhận được", "thu được"]],
  [/恶梦币/, ["đồng tiền ác mộng", "tiền ác mộng"]],
  [/血精/, ["huyết tinh"]],
  [/精血/, ["tinh huyết"]],
  [/獠牙/, ["răng nanh", "nanh"]],
  [/天赋/, ["thiên phú"]],
  [/技能/, ["kỹ năng"]],
  [/物品栏/, ["ô chứa đồ", "vật phẩm"]],
  [/基地石/, ["hòn đá căn cứ", "đá căn cứ"]],
  [/基地/, ["căn cứ"]],
  [/分解/, ["phân giải"]],
  [/编号/, ["mã số", "số hiệu"]],
  [/好友/, ["bạn bè", "kết bạn"]],
  [/聊天频道/, ["kênh trò chuyện", "khung chat"]],
  [/疾风连弩/, ["nỏ liên hoàn tật phong", "nỏ tật phong"]],

  // Creatures & Monsters
  [/怪头黑蚁|黑蚁/, ["kiến đen", "kiến"]],
  [/怪头兵蚁|兵蚁/, ["kiến lính", "kiến"]],
  [/蚂蚁/, ["kiến"]],
  [/野猪|巨型野猪/, ["heo rừng", "lợn rừng", "heo", "lợn"]],
  [/猫|橘猫/, ["mèo", "quất miêu"]],
  [/树蟒|拟色树蟒/, ["trăn", "mộc trăn"]],
  [/死亡蠕虫/, ["giun tử thần", "sâu tử thần"]],
  [/触手/, ["xúc tu"]],
  [/黑刺木/, ["hắc thích mộc"]],

  // Common Novel Words & Verbs
  [/短视频/, ["video", "clip"]],
  [/输血/, ["truyền máu"]],
  [/血型/, ["nhóm máu"]],
  [/血库/, ["ngân hàng máu", "kho máu"]],
  [/黄金血包|黄金血袋/, ["túi máu hoàng kim"]],
  [/催肥饲料/, ["thức ăn tăng trọng", "cám béo"]],
  [/深眠/, ["ngủ say", "ngủ sâu"]],
  [/昏迷/, ["hôn mê"]],
  [/人类/, ["con người", "nhân loại"]],
  [/手术/, ["phẫu thuật"]],
  [/疾病/, ["bệnh"]],
  [/维持/, ["duy trì"]],
  [/生机/, ["sự sống", "sinh cơ"]],
  [/黑暗/, ["đen tối", "tội ác", "hắc ám"]],
  [/产业链/, ["đường dây", "chuỗi"]],
  [/诞生/, ["ra đời", "sinh ra"]],
  [/亲生父母/, ["cha mẹ ruột"]],
  [/流浪/, ["lang thang"]],
  [/洋娃娃/, ["búp bê"]],
  [/扎成筛子/, ["thủng lỗ chỗ như tổ ong", "sàng", "lỗ chỗ"]],
  [/平缓下来/, ["bình tĩnh", "hạ xuống", "bình hoãn"]],
  [/扳机/, ["bóp cò", "bóp lẫy", "cò súng"]],
  [/内部器官/, ["cơ quan nội tạng", "nội tạng"]],
  [/鱼饵/, ["mồi nhử", "mồi câu"]],
  [/皱起眉头|皱眉/, ["nhíu mày", "nhíu chặt"]],
  [/双眼无神/, ["đôi mắt đờ đẫn", "đờ đẫn", "vô hồn"]],
  [/科学/, ["khoa học"]],
  [/霰弹枪/, ["súng săn", "súng bắn hoa cải"]],
  [/体质/, ["thể chất"]],
  [/肉块/, ["khối thịt", "cục thịt", "miếng thịt"]]
];

module.exports = { BILINGUAL_LEXICON };
