<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>false</UseWindowsForms>
    <AssemblyName>TramChuGeminiWebTranslator</AssemblyName>
    <RootNamespace>TramChuGeminiWebTranslator</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>
</Project>
